# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: sha512
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        database_users:
            entity: { class: AppBundle:User, property: githubId }
#        user:
#            entity: { class: AppBundle\Entity\User, property: githubId }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            anonymous: ~
            oauth:
                resource_owners:
                    my_github: "/login/check-github"
                login_path: /
                use_forward: false
                failure_path: /
                oauth_user_provider:
                    service: ib_user.oauth_user_provider
            logout:
                path: /logout
                target: /

    access_control:
#        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/issues, roles: ROLE_USER }
        - { path: ^/issue-view, roles: ROLE_USER }
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~